version: 20.10.17

services:
 db:
    container_name: "tutorial.db"
    build:
     context: .
     dockerfile: db.Dockerfile
    networks:
     - default
    restart: always
    ports:
     - "3036:3036"
    environment: 
     MYSQL_RANDOM_ROOT_PASSWORD: root
     MYSQL_DATABASE: database
     MYSQL_USER:  root
     MYSQL_PASSWORD: root
     volumes:
      mysql_data:app/mysql
     command: --default-authentication-plugin=mysql_native_password
 api:
     container_name: "tutorial.api"
     build: 
      context: .
      dockerfile: api.Dockerfile
     ports:
       - 8000:8000
     depends_on:
       - db
     volumes:
      - .:/app/
networks:
  -default:
volumes:
  -mysql_data:

      

  




